---
- name: Deploy app from GitHub and build Docker image on EC2
  hosts: ec2
  become: true
  vars:
    app_dir: /opt/restful-api
    image_name: restful-api:latest

  tasks:

    - name: Install required packages
      apt:
        name:
          - docker.io
          - nginx
          - git
        update_cache: yes
        state: present

    - name: Ensure Docker is started
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Remove any previous contents from app directory
      file:
        path: "{{ app_dir }}"
        state: absent
      ignore_errors: true

    - name: Recreate app directory
      file:
        path: "{{ app_dir }}"
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Clone the application repository
      git:
        repo: https://github.com/Virusmk13/Restfull-API.git
        dest: "{{ app_dir }}"
        version: main
        force: yes

    - name: Build Docker image from the cloned repo
      community.docker.docker_image:
        name: "{{ image_name }}"
        build:
          path: "{{ app_dir }}"
        source: build
        state: present

    - name: Run the Docker container from local image
      community.docker.docker_container:
        name: restful-api
        image: "{{ image_name }}"
        ports:
          - "8080:8080"
        state: started
        restart_policy: always
        env:
          DB_HOST: "{{ rds_host }}"
          DB_PORT: "{{ rds_port }}"
          DB_NAME: "{{ rds_name }}"
          DB_USER: "{{ rds_user }}"
          DB_PASSWORD: "{{ rds_password }}"

    - name: Configure Nginx reverse proxy
      copy:
        dest: /etc/nginx/sites-available/restful-api
        content: |
          server {
              listen 80;
              server_name _;
              location / {
                  proxy_pass http://localhost:8080;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
              }
          }

    - name: Enable Nginx site config
      file:
        src: /etc/nginx/sites-available/restful-api
        dest: /etc/nginx/sites-enabled/restful-api
        state: link
        force: yes

    - name: Remove default Nginx config
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Restart Nginx
      systemd:
        name: nginx
        state: restarted
