---
- name: Upload Unity project from GitHub Actions to EC2
  hosts: ec2
  become: true
  vars:
    project_dir: /opt/unity-game

  tasks:
    - name: Ensure target directory is absent
      file:
        path: "{{ project_dir }}"
        state: absent
        force: true

    - name: Create project directory
      file:
        path: "{{ project_dir }}"
        state: directory
        mode: '0755'

    - name: Upload Unity project from runner to EC2
      copy:
        src: ./ 
        dest: "{{ project_dir }}/"
        mode: '0755'

    - name: Confirm upload success
      shell: ls -l "{{ project_dir }}"
      register: listing

    - name: Show uploaded files
      debug:
        var: listing.stdout_lines
