---
- name: Clone Unity game repository on EC2
  hosts: ec2
  become: true
  vars:
    repo_url: https://github.com/Virusmk13/Licenta.git
    project_dir: /opt/unity-game

  tasks:
    - name: Install Git
      apt:
        name: git
        state: present
        update_cache: yes

    - name: Ensure target directory is absent (clean clone)
      file:
        path: "{{ project_dir }}"
        state: absent
        force: true

    - name: Clone the Unity project repository
      git:
        repo: "{{ repo_url }}"
        dest: "{{ project_dir }}"
        version: main
        force: yes
