---
- name: Upload Unity project from GitHub Actions to EC2
  hosts: ec2
  become: true
  vars:
    project_dir: /opt/unity-game

  tasks:
    - name: Clean up old project, Ansible temp files, and free up disk space
      shell: |
        rm -rf {{ project_dir }} ~/.ansible /tmp/* /var/tmp/* /var/log/*
        apt-get clean
        journalctl --rotate
        journalctl --vacuum-time=1d || true
        sync
        echo 3 > /proc/sys/vm/drop_caches
      args:
        warn: false

    - name: Create fresh project directory
      file:
        path: "{{ project_dir }}"
        state: directory
        mode: '0755'

    - name: Upload Unity project from runner to EC2
      copy:
        src: ./  # repo e deja checkout în GitHub Actions
        dest: "{{ project_dir }}/"
        mode: '0755'

    - name: List uploaded files
      shell: ls -l "{{ project_dir }}"
      register: listing

    - name: Show uploaded files
      debug:
        var: listing.stdout_lines

    - name: Check disk space on EC2
      shell: df -h
      register: disk_output

    - name: Show free disk space
      debug:
        var: disk_output.stdout_lines
