---
- name: Setup EC2 for Task Manager App
  hosts: ec2_instances
  become: yes
  vars:
    app_dir: "/home/ubuntu/task-manager"
    database_url: "postgresql://postgres:12345678@taskmanagerapi-db.c1c2cquoaakb.eu-north-1.rds.amazonAaws.com:5432/taskmanagerapi-db"
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install required packages
      apt:
        name:
          - python3-pip
          - python3-venv
          - git
          - libpq-dev
        state: present

    - name: Clone the repository
      git:
        repo: 'https://github.com/Virusmk13/Task-Manager-API'
        dest: "{{ app_dir }}"
        version: main

    - name: Set environment variable for database connection
      copy:
        content: "DATABASE_URL={{ database_url }}\n"
        dest: "{{ app_dir }}/.env"

    - name: Create a virtual environment
      command: python3 -m venv venv
      args:
        chdir: "{{ app_dir }}"

    - name: Install Python packages
      pip:
        name:
          - fastapi
          - uvicorn
          - sqlalchemy
          - psycopg2-binary
          - python-dotenv
          - pydantic
        state: present

    - name: Start the application with Uvicorn
      command: uvicorn main:app --host 0.0.0.0 --port 80 --reload
      args:
        chdir: "{{ app_dir }}"
      async: 3600
      poll: 0
