name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Set up SSH
        shell: bash
        run: |
          mkdir -p "$HOME/.ssh"
          echo "${{ secrets.EC2_KEY }}" > "$HOME/.ssh/id_rsa"
          chmod 600 "$HOME/.ssh/id_rsa"
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> "$HOME/.ssh/known_hosts"

      - name: Create Ansible inventory
        run: |
          echo "[ec2]" > inventory
          echo "${{ secrets.EC2_HOST }} ansible_user=${{ secrets.EC2_USER }} ansible_ssh_private_key_file=$HOME/.ssh/id_rsa" >> inventory

      - name: Run Ansible playbook
        run: |
          ansible-playbook Deploy.yml -i inventory
